language: ruby
bundler_args: --standalone
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - gemfiles/activerecord_3_1.gemfile
  - gemfiles/activerecord_3_2.gemfile
  - gemfiles/activerecord_4.gemfile
  - gemfiles/activerecord_edge.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/activerecord_4.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/activerecord_edge.gemfile
branches:
  only:
    - master
