language: ruby
bundler_args: --without development --standalone
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - ci/Gemfile.ar3.1
  - ci/Gemfile.ar-edge
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: ci/Gemfile.ar-edge
